apim_rg                  = "rg-apim-me-dev-canadacentral-001"
apim_name                = "apim-me-dev-canadacentral-001"
apim_gateway_name        = "alibaba-cloud-china"
apim_gateway_description = "jm-gateway2-canada-central1"
apim_gateway_region      = "alicloud-kubernetes-cluster"
# kv_name                  = "kv-jm-sre-lbuc"
# kv_rg                    = "sre-rg"